default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :beta do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_options: {
        method: "app-store",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: true
      }
    )
    upload_to_testflight
  end

  desc "Deploy to Firebase App Distribution"
  lane :firebase do
    firebase_app_distribution(
      app: "1:865073764375:ios:dc1909046b2b50f5cee452",
      testers: "testers@example.com",
      release_notes: "Automated build"
    )
  end
end
