name: iOS Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
    - name: update dependencies
      run: flutter pub upgrade

    - name: Install dependencies
      run: flutter pub get

    - name: Update iOS Deployment Target
      run: |
        sed -i '' 's/platform :ios, '9.0'/platform :ios, '14.0'/' ios/Podfile
        if ! grep -q "platform :ios, '14.0'" ios/Podfile; then
          echo "platform :ios, '14.0'" >> ios/Podfile
        fi 

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        cd ..

    - name: Set up Fastlane
      run: |
        cd ios
        bundle install
        cd ..

    - name: Deploy to TestFlight
      run: |
        cd ios
        bundle exec fastlane beta
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }} 
        APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }} 
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}

    - name: Deploy to Firebase App Distribution
      if: success()
      run: |
        cd ios
        bundle exec fastlane firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}